# Site Info
title:              "Learning Cryptography the Hard Way"
description:        "Articles and resources about cryptography"
google_verify:      abc123 # Put your Google Verification here
google_analytics:   UA-123

# Author Info
author_name:        "Juan M Salamanca" # Your name here
author_email:       jumisz.dev@gmail.com # Your email here
author_gravatar:    e98e5de03e97f8498caab87e85a43f9a # Your Gravatar md5 hash here for logo

# Site Settings
url:                 https://navasvarela.github.io/learning-cryptography/ # Change to your site
baseurl:
permalink:          /posts/:title # Post permalink
timezone:           Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
